-- AlterTable
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "scheduleDay" TEXT;
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "scheduleTime" TEXT;
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "weightAttendance" DOUBLE PRECISION DEFAULT 10;
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "weightAssignment" DOUBLE PRECISION DEFAULT 20;
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "weightPretest" DOUBLE PRECISION DEFAULT 10;
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "weightUts" DOUBLE PRECISION DEFAULT 25;
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "weightUas" DOUBLE PRECISION DEFAULT 35;
